### ISSUE TITLE
app was crashed 

### ISSUE THREAD

**Issue by dineshswaas** [appunite/AndroidFFmpeg#155]
05-30 13:57:37.403 19169-19169/com.ffmpegtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.ffmpegtest, PID: 19169
                                                                java.lang.UnsatisfiedLinkError: Couldn't load nativetester-jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ffmpegtest-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ffmpegtest-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                    at java.lang.System.loadLibrary(System.java:526)
                                                                    at com.appunite.ffmpeg.NativeTester.<clinit>(NativeTester.java:23)
                                                                    at com.appunite.ffmpeg.FFmpegPlayer.<clinit>(FFmpegPlayer.java:184)
                                                                    at com.ffmpegtest.VideoActivity.onCreate(VideoActivity.java:138)
                                                                    at android.app.Activity.performCreate(Activity.java:5264)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by tanjinc** [comment]
I saw the same problem. because the *.so is not exist
